### GET all categories
GET http://localhost:3000/api/category
Accept: application/json

###

### POST: Create new category
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "name": "Bún Chả",
  "slug": "bun-bo",
  "parent_id": "685906923158242d4fde4c22",
  "image": "https://example.com/bun-cha.jpg",
  "is_active": true
}

###

### PUT: Update category
PUT http://localhost:3000/api/category
Content-Type: application/json

{
  "id": "664fbd9e23cfb0c6c8e0d8f2",
  "name": "Bún Chả Cua",
  "slug": "bun-cha-ha-noi",
  "parent_id": "685906923158242d4fde4c22",
  "image": "https://example.com/bun-cha-hn.jpg",
  "is_active": true
}

###

### DELETE: Delete category
DELETE http://localhost:3000/api/category
Content-Type: application/json

{
  "id": "664fbd9e23cfb0c6c8e0d8f2"
}
