### List all products
GET http://localhost:3000/api/products?page=1&limit=10
Accept: application/json

### Search/filter products
GET http://localhost:3000/api/products?status=published&brand_id=685904633158242d4fde4c17&search=ao-thun&page=1&limit=10
Accept: application/json

### Get product detail
GET http://localhost:3000/api/products/68590e78a2624c42c76556b6
Accept: application/json

### Create new product
POST http://localhost:3000/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "Áo sơ mi tay ngắn",
  "slug": "ao-so-mi-tay-ngan-chao",
  "description": "Cotton 100%",
  "brand_id": "685904633158242d4fde4c17",
  "category_ids": ["685906923158242d4fde4c22", "685906e13158242d4fde4c2b"],
  "tags": ["nam", "cotton"],
  "status": "draft"
}

### Update product
PUT http://localhost:3000/api/products/68590e78a2624c42c76556b6
Content-Type: application/json
Accept: application/json

{
  "name": "Áo sơ mi tay dài",
  "description": "Cotton 100% - updated",
  "tags": ["nam", "cotton", "dai-tay"],
  "status": "published"
}

### Delete product
DELETE http://localhost:3000/api/products/685906923158242d4fde4c22
Accept: application/json
